# K 7.W.1 — DuckDB workspace setup cell
# Generated by AI for pipeline-kata.ipynb Cell 1
# Compatible with local Jupyter and Google Colab

import subprocess, sys

subprocess.run(
    [sys.executable, "-m", "pip", "install", "duckdb", "pandas", "--quiet"],
    check=True,
)

import duckdb
import pandas as pd
import os
import random
import numpy as np
from datetime import datetime

# In-memory DuckDB connection
con = duckdb.connect()

# Create hello_world table
con.execute("""
    CREATE TABLE hello_world (
        id        INTEGER,
        message   VARCHAR,
        created_at TIMESTAMP
    )
""")

# Insert 3 sample rows
con.execute("""
    INSERT INTO hello_world VALUES
        (1, 'Hello from DuckDB!',    '2024-01-15 09:00:00'),
        (2, 'Pipeline kata ready.',  '2024-01-15 09:01:00'),
        (3, 'Let the data flow.',    '2024-01-15 09:02:00')
""")

# Query and display
result = con.execute("SELECT * FROM hello_world").fetchdf()
print(result.to_string(index=False))

print("\nEnvironment ready ✓")
